name: Workflow File

on:
  workflow_dispatch:
  push:
    branch:
      - master

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -lart