name: workflow file with on 

on:
  workflow_dispatch:
  pull_request:
    [open, closed, synchronize]
  push:
    branches:
      - master
  
concurrency:
  cancel-in-progress: true

jobs:
  workflow-file-on:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: list directory content
        run: ls -lart